volumes:
  postgres-data:
  redis-data:
  pg-admin:

services:
  app:
    # platform: linux/amd64
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      # privileged: true
      args:
        # Update 'VARIANT' to pick an version of Java: 11, 17.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  cache:
    image: redis/redis-stack:latest
    network_mode: service:app
    restart: unless-stopped
    # command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    # Add "forwardPorts": ["6379"] to **devcontainer.json** to forward redis locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  nginx:
    image: nginx:latest
    network_mode: service:app
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
      # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)
      # command: >
      #   sh -c "chmod +x /usr/local/bin/config-nginx.sh &&
      #         /usr/local/bin/config-nginx.sh"

  db:
    image: postgres:latest
    network_mode: service:app
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
      # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin:
    image: dpage/pgadmin4
    network_mode: service:app
    restart: unless-stopped
    volumes:
      - pg-admin:/var/lib/pgadmin
    env_file:
      - .env
      # Add "forwardPorts": ["5050"] to **devcontainer.json** to forward PgAdmin locally.

      # flower:
      #   image: mher/flower:latest
      #   network_mode: service:app
      #   volumes:
      #     - ./flower-client.py:/data/flower-client.py
      #   restart: unless-stopped
      #   entrypoint: ["celery", "-A", "flower-client", "flower", "--enable_events"]
      #   environment:
      #     # - BROKER_URL=redis://localhost:6379/0
      #     - FLOWER_PORT=5555
      #   # Add "forwardPorts": ["5555"] to **devcontainer.json** to forward Flower locally.
      #   # (Adding the "ports" property to this file will not forward from a Codespace.)
